test: allow bootstrap tests to succeed when targeted toolchains already exist (#695)
Currently, running tests locally as described in
[`dev.md`](https://github.com/leanprover/vscode-lean4/blob/master/docs/dev.md)
works at most one time.
In subsequent runs, the user's local `elan` installation already has the
test and build toolchains installed.
This causes `elan toolchain install leanprover/lean4:x-y-z` to fail with
the message
```
error: 'leanprover/lean4:x-y-z' is already installed
```

This PR makes the assertion succeed if the `...is already installed`
error is printed, even if the exit code indicates failure.
This allows the test suit to be run multiple times locally.